### ISSUE TITLE
Allow pre-populating of the address fields

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-wpuser-integration#12]
Codebase https://events.codebasehq.com/projects/event-espresso/tickets/8038

Per @lorenzocaum 
The WP User integration currently pre-populates the name and email fields. Could we also pre-populate the address fields?

The version for Event Espresso 3 currently populates the name, email, and address fields.

Requested:

http://eventespresso.com/topic/invoice-html-event_excerpt-starts-with-for/
https://eventespresso.com/topic/ee4-wp-user-integration-pre-fill-custom-fields-and-custom-registration-fields/
http://eventespresso.com/topic/linking-questions-to-user-meta-in-ee4-autofilling-registration/#post-180879
http://eventespresso.com/topic/ee4-does-not-autofill-addresse-information-for-example/#post-181445

Per @joshfeck 

This snippet auto-fills the address questions
https://github.com/eventespresso/ee-code-snippet-library/blob/master/addons/eea-wp-user/jf_filter_address_answer_for_wpuser.php

**Comment by joshfeck** [comment]
If it's ever decided this is something that's needed to add without using the filter function, we can reopen this.
