### ISSUE TITLE
Update date and time strings in ESPRESSO_MY_EVENTS templates so they're i18n-ready

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-wpuser-integration#16]
Currently they output dates that don't translate. Might just need to wrap all dates with date_i18n().

**Comment by Pebblo** [comment]
The only place I found that is not already i18n ready was a section that used `$ticket->date_range()` so the fix for that method would be in core.

So I've created https://github.com/eventespresso/event-espresso-core/pull/1133 for that fix.

**Comment by joshfeck** [comment]
Fixed in core, https://github.com/eventespresso/event-espresso-core/pull/1133
