### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dcdigit** [eventespresso/eea-wpuser-integration#22]
https://github.com/eventespresso/eea-wpuser-integration/blob/0762c1bcfb129b1a1ac05c5fda42d81ccbbb0acf/EED_WP_Users_SPCO.module.php#L1251

registration not regsitration

**Comment by mnelson4** [comment]
Thanks @dcdigit. I have a PR here to address that: https://github.com/eventespresso/eea-wpuser-integration/pull/23
