### ISSUE TITLE
Load assets deployed from barista

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/eea-wpuser-integration#30]
Since the JS code is managed in barista, which will be deployed here. We need to load those assets for EDTR.

**NOTE:** Assets are deployed to `barista` branch and old assets are no longer in that branch.

**Comment by tn3rb** [comment]
already taken care of by this one little line of code in `EventEspresso\WpUser\domain\entities\routing\EspressoEventEditor::initialize()`

```php
$this->initializeBaristaForDomain(Domain::class);
```

> old assets are no longer in that branch.

ya that's not good... that nuked a bunch of functionality for that add-on 😆 

plz see: https://github.com/eventespresso/barista/pull/494

**Comment by manzoorwanijk** [comment]
> ya that's not good... that nuked a bunch of functionality for that add-on

Ya, that was actually the reason to create `barista` branch, otherwise I could set up the deployments directly to master.

**Comment by manzoorwanijk** [comment]
The priority for the assets needs to be fixed to make sure the addon assets are loaded before core assets. This is to make sure the UI elements are registered before the core UI elements are rendered.

**Comment by manzoorwanijk** [comment]
Fixed via https://github.com/eventespresso/eea-wpuser-integration/commit/ffb7e4ab63ee008df8f705e11dc397210dd1b845
