### ISSUE TITLE
GQL Schema registration not fired.

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/eea-wpuser-integration#32]
Steps:
- Goto [https://barista.eventespresso.com/wp-admin/admin.php?page=graphiql-ide](https://barista.eventespresso.com/wp-admin/admin.php?page=graphiql-ide)
- Select `GET_TICKETS` from the History
- Notice the error for `capabilityRequired` field

It simply means that the GQL schema registration is not fired. May be because of some addon registration changes?

**Comment by tn3rb** [comment]
the callback for `FHEE__EventEspresso_core_domain_services_graphql_types__ticket_fields` is `\EventEspresso\WpUser\domain\services\graphql\RegisterSchema::registerCoreTicketFields()`

which creates the `capabilityRequired` field like this:

```phpnew GraphQLField(
    'capabilityRequired',
    'String',
    null,
    esc_html__('WP User Capability required for purchasing this ticket.', 'event_espresso'),
    null,
    [$this, 'getCapabilityRequired']
),
```


I've noticed that some other schemas use `GraphQLInputField()` and `GraphQLOutputField()`.
I've assumed that the latter isa GQL only field that does not have a corresponding database field, but have never grokked what the former is for... but do we maybe need to use `GraphQLInputField()` for the `capabilityRequired` field?

**Comment by manzoorwanijk** [comment]
That is not the issue here. After debugging, I found that `\EventEspresso\WpUser\domain\services\graphql\RegisterSchema::addHooks` is called after `FHEE__EventEspresso_core_domain_services_graphql_types__ticket_fields` filters are applied.

FYI:
- `GraphQLField` means that the field is a part of the entity i.e. `query` as well as the mutation input object.
- `GraphQLInputField` means the field is registered only for mutation input.
- `GraphQLOutputField` means the field is registered only for the entity query, not the mutation input. e.g. `isSoldOut` is not updated via mutations, rather it's calculated, that is why it's output only field.
