### ISSUE TITLE
Ticket capabilities meta is not reflected in EDTR DOM data

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/eea-wpuser-integration#40]
When a ticket with custom caps is updated, the data gets saved to the DB but same is not reflected in EDTR DOM data. After debugging, I found that the cause of the issue is the order of filters from Core and WP User Addon (WPUA).

WPUA hooks into this filter of Core to set the ticket capabilities data
`FHEE__EventEspresso_core_domain_entities_routing_data_nodes_domains_EventEditor__initialize__related_data`
but WPUA adds the capabilities data to the DOM data using
`EventEspresso\WpUser\domain\entities\routing\WpUserData::addTicketMetaData()` which is executed inside `initialize()` method of the same class which is called before the above Core filter is run. Thus the ticket capabilities data is always the default value (empty array).

**Solution:** `EventEspresso\WpUser\domain\entities\routing\WpUserData::initialize()` needs to run after the above core filter.

**Comment by tn3rb** [comment]
🕵🏻 great detective work thnx

will push a fix in a bit
