### ISSUE TITLE
Undefined Constant EE_FRONT_AJAX in eea-wpuser-integration/EED_WP_Users_SPCO.module.php, l. 121

### ISSUE THREAD

**Issue by christophhapple** [eventespresso/eea-wpuser-integration#45]
## Issue Overview

Dear Event Espresso Team

I am getting fatal errors when trying to disconnect my Stripe Gateway. However, I assume the issue to be broader than any specific payment gateway or payment gateways in general.

It seems Event Espresso has trouble communicating with Wordpress/Database via Ajax Requests because a constant used is undefined. As of PHP 8, this is a fatal error and not just a warning.

Under related information you will find a pull requests and commits that already addressed this problem (in core). It seems to me that another case of this was missed in this addon here. Maybe there are other cases stil.

Cheers,
Chris

## Bug report or feature request?

* [X] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 4.10.24.p

Version of this addon: 2.0.17.p

Version of WordPress: 5.8.2

PHP Version:  8.0.14

Browser used:  Google Chrome - Version 97.0.4692.71 (Official Build) (x86_64)

## Steps to Reproduce (for bugs)

- Get current plugin and addon
- Go to Wordpress Backend > Event Espresso > Settings > Payment Methods > Stripe
(/admin.php?page=espresso_payment_settings)
- Try to connect or disconnect a Stripe account

## Expected Behaviour

Stripe account should connect / disconnect as planned.

## Current Behaviour

Operation fails, loading icon keeps spinning and a request to /admin-ajax.php returns a 5XX response.

Consulting PHP Logs reveals the following message:

PHP Fatal error:  Uncaught Error: Undefined constant "EE_FRONT_AJAX" in /.../eea-wp-user-integration/EED_WP_Users_SPCO.module.php:121

## Related Information:

I searched and found issues and a pull request addressing the same constant being used when undefined.
Seems these efforts just didn't catch all the problematic cases?

PR: https://github.com/eventespresso/event-espresso-core/pull/3605/commits
Commits:
https://github.com/eventespresso/event-espresso-core/pull/3605/commits/e6896c6023d9946fcc25187cc6d281a5a10aed95
https://github.com/eventespresso/event-espresso-core/pull/3605/commits/d397032cc285350bc523441d74b6c8733480cf26

A workaround can be straightforward, implementing the same checks as in the commits above and will solve the problem for me in this instance.
However, this requires monkey-patching plugin files, which of course is not a stable solution.

**Comment by hoseinrafiei** [comment]
@tn3rb

I just faced this issue Today and I applied a PR to fix it.
The code that I committed just fix the PHP warning but I prefer to know why that constant is undefined and fix it by defining it on the correct place. Please check the PR and let me know your feedback.
