### ISSUE TITLE
Add option to promotion editor to apply promotions for only logged in registered users

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-wpuser-integration#6]
Codebase ticket: https://events.codebasehq.com/projects/event-espresso/tickets/8147

This feature would appear if WP User integration is active and will limit guests from being able to use coupon codes and/or promotions.

This could be a per promotion option which makes the promotion (code or no code) only apply if the registrant is logged into the site while they register.

**Comment by sethshoultes** [comment]
This is already in the backlog

**Comment by nerrad** [comment]
sure, I was just restoring the label it had before stale bot added its stale label.  In other words you had never removed the `status:triage` label when you removed it too the backlog.  Would it be useful to add more descriptive labels to the issue instead of leaving it with no labels?

**Comment by sethshoultes** [comment]
Ah, thanks. I didn't realize I forgot to remove that label. Yes, it would be nice if maybe a label was applied that reflects the current pipeline it's in.

**Comment by nerrad** [comment]
Personally I don't find the labels related to pipelines to be that useful (it's redundant).  I was thinking more along the lines labels that help indicate at a glance things like:

- is the label a bug?  Is it a feature?
- what category does this fit in?

If we're not going to use those things then maybe it'd save time to just not bother maintaining all the labels we have?

**Comment by sethshoultes** [comment]
Ah, yes, sorry I misunderstood. I agree with using labels to describe things such as features, bugs, etc. I try to use them whenever possible but maybe this repo didn't have labels at the time the ticket was created or I just forgot when I created the ticket.
